name: Deploy to Azure Static Web Apps (Pa-POC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install & Build (Vite/React)
        working-directory: web
        run: |
          npm ci || npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use YOUR secret name exactly as created
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FOREST_0716B3A0F }}
          action: "upload"
          app_location: "."                 # not used when we provide artifact
          app_artifact_location: "web/dist" # upload this folder as-is
          skip_app_build: true              # prevents Oryx build
