name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      # Build the frontend ourselves (includes devDependencies like vite)
      - name: Install & Build (Vite/React)
        working-directory: web
        run: |
          npm ci || npm install
          npm run build

      # Upload the *built* artifact; skip Oryx build entirely
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "."                  # root of repo (doesn't matter since we provide artifact)
          app_artifact_location: "web/dist"  # <-- upload this folder as-is
          skip_app_build: true               # <-- prevents Oryx from re-building
